This document is a base User Manual of the {company_name} {wl-product-name-portal}.

This manual provides all the necessary guides to understand and use the different components provided on the {wl-product-name-portal}, so as to make meaningful representation and visualisation of the Data sent from the Machines.

The manual is targeted to users with little to no knowledge about {company_name} Product(s) or End to End Solutions.

Access to the data portal is secure and managed by an easily configurable way to assign <<User Permissions, User Permissions>> so that different types of users can be created (Administrator, Maintainer, Users) to access the data using the Visual tools found with the Portal.

The {wl-product-name-portal} is a REST based Web Application and the Data on the {wl-product-name-portal} is also accessible using the REST API.

The REST API is <<AEMP compliant, AEMP compliant>> and the Documentation is available at {api_url}


:leveloffset: +2
== How to use this Document
:leveloffset: 0

This document describes all the components of the {wl-product-name-portal} Cloud Application and how to configure and use each of them.

 - For User within a Group or Organisation Unit then this is a good to start at the beginning of the Document

 - Each User has a minimum Administration Facility as explained in section <<Admin Overview, Admin Overview>>

For OEM and Administrator, it is advisable to do plan and start with the <<Admin Overview, Admin Overview>>

 - To create a Hierarchical Tree of the Organisation Units.

 - To assign the Machines and Users to the required Organisation Units

<<<